// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahgglzmotxjajhacqopn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZ2dsem1vdHhqYWpoYWNxb3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzI0ODMsImV4cCI6MjA3Mzk0ODQ4M30.5txk7rs4KdoDBoOTdWaN0fm8YdCO2Ji8NmfzKGiiXrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});